#!/bin/bash

docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg VCS_URL="https://github.com/pocketfulofrage/docker-nxfilter" \
    --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
    --build-arg VERSION=`cat version.txt` \
  -t $IMAGE_NAME .
